services:
  - type: web
    name: promptect-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000 --workers 2 --proxy-headers --forwarded-allow-ips="*"
    autoDeploy: true
    healthCheckPath: /auth/health
    plan: free
